// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Reanimated from "../Reanimated.bs.js";
import * as ReactNativeReanimated from "react-native-reanimated";

var container = {
  backgroundColor: "black",
  flex: 1
};

var flex = {
  flex: 1
};

var blue = {
  backgroundColor: "blue"
};

var content = {
  backgroundColor: "white",
  height: 1000
};

var Styles = {
  container: container,
  flex: flex,
  blue: blue,
  content: content
};

function UseAnimatedScrollHandlerExample(Props) {
  var translationY = ReactNativeReanimated.useSharedValue(0);
  var scrollHandler = ReactNativeReanimated.useAnimatedScrollHandler({
        onScroll: (function ($$event) {
            translationY.value = $$event.contentOffset.y;
          })
      });
  var animatedStyles = ReactNativeReanimated.useAnimatedStyle(function () {
        return {
                transform: [{
                    translateY: translationY.value
                  }]
              };
      });
  return React.createElement(Reanimated.View.make, {
              style: container,
              children: null
            }, React.createElement(Reanimated.View.make, {
                  style: [
                    animatedStyles,
                    flex,
                    blue
                  ]
                }), React.createElement(Reanimated.ScrollView.make, {
                  onScroll: scrollHandler,
                  scrollEventThrottle: 16,
                  style: flex,
                  children: React.createElement(Reanimated.View.make, {
                        style: content,
                        children: React.createElement(Reanimated.$$Text.make, {
                              children: "really cool content here!"
                            })
                      })
                }));
}

var make = UseAnimatedScrollHandlerExample;

var $$default = UseAnimatedScrollHandlerExample;

export {
  Styles ,
  make ,
  $$default ,
  $$default as default,
}
/* react Not a pure module */
