// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exports from "./exports";

var make = Exports.AnimatedView;

var View = {
  make: make
};

function Make(Arguments) {
  return {};
}

var AnimatedGestureHandler = {
  Make: Make
};

function make$1(smth) {
  return {
          value: smth
        };
}

var SharedValue = {
  make: make$1
};

var Extrapolation = {};

var ExtrapolationType = {};

var Interpolate = {};

export {
  View ,
  AnimatedGestureHandler ,
  SharedValue ,
  Extrapolation ,
  ExtrapolationType ,
  Interpolate ,
  
}
/* make Not a pure module */
