// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exports from "./exports";
import * as ReactNativeReanimated from "react-native-reanimated";

var make = Exports.AnimatedView;

var View = {
  make: make
};

var make$1 = Exports.AnimatedText;

var $$Text = {
  make: make$1
};

function Make(Arguments) {
  return {};
}

var AnimatedGestureHandler = {
  Make: Make
};

function make$2(smth) {
  return {
          value: smth
        };
}

var SharedValue = {
  make: make$2
};

var Easing = {};

function makeConfig(duration, easing, param) {
  return {
          duration: duration,
          easing: easing
        };
}

var Timing = {
  makeConfig: makeConfig
};

function withTiming(toValue, userConfig, callback, param) {
  return ReactNativeReanimated.withTiming(toValue, userConfig, callback);
}

function makeConfig$1(mass, stiffness, overshootClamping, restDisplacementThreshold, restSpeedThreshold, velocity, damping, param) {
  return {
          mass: mass,
          stiffness: stiffness,
          overshootClamping: overshootClamping,
          restDisplacementThreshold: restDisplacementThreshold,
          restSpeedThreshold: restSpeedThreshold,
          velocity: velocity,
          damping: damping
        };
}

var Spring = {
  makeConfig: makeConfig$1
};

function withSpring(toValue, userConfig, callback, param) {
  return ReactNativeReanimated.withSpring(toValue, userConfig, callback);
}

var Extrapolation = {};

var ExtrapolationType = {};

var Interpolate = {};

export {
  View ,
  $$Text ,
  AnimatedGestureHandler ,
  SharedValue ,
  Easing ,
  Timing ,
  withTiming ,
  Spring ,
  withSpring ,
  Extrapolation ,
  ExtrapolationType ,
  Interpolate ,
  
}
/* make Not a pure module */
